import type {
  DistrictOption,
  ILocationLookup,
  ProvinceOption,
} from './LocationLookup';

const PROVINCES_BY_CODE: Record<string, string> = {
  'prov-01': 'Adana',
  'prov-02': 'Adıyaman',
  'prov-03': 'Afyonkarahisar',
  'prov-04': 'Ağrı',
  'prov-05': 'Amasya',
  'prov-06': 'Ankara',
  'prov-07': 'Antalya',
  'prov-08': 'Artvin',
  'prov-09': 'Aydın',
  'prov-10': 'Balıkesir',
  'prov-11': 'Bilecik',
  'prov-12': 'Bingöl',
  'prov-13': 'Bitlis',
  'prov-14': 'Bolu',
  'prov-15': 'Burdur',
  'prov-16': 'Bursa',
  'prov-17': 'Çanakkale',
  'prov-18': 'Çankırı',
  'prov-19': 'Çorum',
  'prov-20': 'Denizli',
  'prov-21': 'Diyarbakır',
  'prov-22': 'Edirne',
  'prov-23': 'Elazığ',
  'prov-24': 'Erzincan',
  'prov-25': 'Erzurum',
  'prov-26': 'Eskişehir',
  'prov-27': 'Gaziantep',
  'prov-28': 'Giresun',
  'prov-29': 'Gümüşhane',
  'prov-30': 'Hakkari',
  'prov-31': 'Hatay',
  'prov-32': 'Isparta',
  'prov-33': 'Mersin',
  'prov-34': 'İstanbul',
  'prov-35': 'İzmir',
  'prov-36': 'Kars',
  'prov-37': 'Kastamonu',
  'prov-38': 'Kayseri',
  'prov-39': 'Kırklareli',
  'prov-40': 'Kırşehir',
  'prov-41': 'Kocaeli',
  'prov-42': 'Konya',
  'prov-43': 'Kütahya',
  'prov-44': 'Malatya',
  'prov-45': 'Manisa',
  'prov-46': 'Kahramanmaraş',
  'prov-47': 'Mardin',
  'prov-48': 'Muğla',
  'prov-49': 'Muş',
  'prov-50': 'Nevşehir',
  'prov-51': 'Niğde',
  'prov-52': 'Ordu',
  'prov-53': 'Rize',
  'prov-54': 'Sakarya',
  'prov-55': 'Samsun',
  'prov-56': 'Siirt',
  'prov-57': 'Sinop',
  'prov-58': 'Sivas',
  'prov-59': 'Tekirdağ',
  'prov-60': 'Tokat',
  'prov-61': 'Trabzon',
  'prov-62': 'Tunceli',
  'prov-63': 'Şanlıurfa',
  'prov-64': 'Uşak',
  'prov-65': 'Van',
  'prov-66': 'Yozgat',
  'prov-67': 'Zonguldak',
  'prov-68': 'Aksaray',
  'prov-69': 'Bayburt',
  'prov-70': 'Karaman',
  'prov-71': 'Kırıkkale',
  'prov-72': 'Batman',
  'prov-73': 'Şırnak',
  'prov-74': 'Bartın',
  'prov-75': 'Ardahan',
  'prov-76': 'Iğdır',
  'prov-77': 'Yalova',
  'prov-78': 'Karabük',
  'prov-79': 'Kilis',
  'prov-80': 'Osmaniye',
  'prov-81': 'Düzce',
};

/** Deterministic UUID v5 for Turkey provinces (generated by BE StableProvinceID). */
const PROVINCES_BY_UUID: Record<string, string> = {
  '802aa4c5-68d5-56e3-b5d8-c98b5d7f7874': 'Adana',
  'fa368f15-052c-58bd-8c22-af7643521553': 'Adıyaman',
  'c6cb4581-16fa-5faf-a4be-4c903baea061': 'Afyonkarahisar',
  '37e6351b-f88f-5b1e-8e6c-ba9c16c079d9': 'Ağrı',
  '104e21e3-a95a-5059-a63e-4058e5682dd0': 'Amasya',
  '2436cf3e-a250-511c-aa39-c5cd1c8a3f71': 'Ankara',
  '14585377-9641-5080-8462-ce6478d58998': 'Antalya',
  'd354d0ab-81ea-560c-ab4d-78ae1be3728a': 'Artvin',
  '4dfde5a5-7180-5cca-929a-96ee235d64f6': 'Aydın',
  'd4a872c2-5cf4-5342-9922-13dc022b290c': 'Balıkesir',
  '7c13f530-e799-51fe-ac09-a231cea4c1e7': 'Bilecik',
  'c6140cb5-5223-57f1-8863-bc925ba91e40': 'Bingöl',
  '85c5a693-64df-5bd9-a36e-977d5009cc9d': 'Bitlis',
  '16ec38a8-998d-5434-b2c7-c03e37ce0f82': 'Bolu',
  '4dfb23b5-1a55-595e-bdb7-9e863c122a10': 'Burdur',
  '47ff002c-f6f2-5c01-81a9-460b23ba9712': 'Bursa',
  'c46e86e7-5849-57bd-b16a-f4ac20d45c0e': 'Çanakkale',
  '64891a60-9e8b-5816-a5cc-cd79d8020a8f': 'Çankırı',
  '1f3d27ad-19e5-5ed5-8b11-09a431437376': 'Çorum',
  'c4f64530-3327-5c22-ba69-2dddca1d6e2e': 'Denizli',
  'b564f517-782a-51c4-9abf-a59ecfa62cc4': 'Diyarbakır',
  '3e06f957-1c15-503a-8bbc-01fbdad0107d': 'Edirne',
  'b9411ebc-c3d7-5ec7-a018-ff029831c002': 'Elazığ',
  '171805e7-c069-5516-947f-5a916285731f': 'Erzincan',
  '3bd7ddd4-06a9-5ce3-843c-b70db66391cc': 'Erzurum',
  'f99e4649-2d13-539a-92e1-12b7c6d03b12': 'Eskişehir',
  '19c22d95-f1f1-527f-b285-73156ced680e': 'Gaziantep',
  'ae7689a4-144a-5d86-86f8-afa06852692d': 'Giresun',
  '4d2aac2d-83bc-5c95-a213-7d7f26474cf2': 'Gümüşhane',
  'a4c5772b-0229-5fdc-abd1-a6ef99070af6': 'Hakkari',
  'b23f1024-95ad-509e-baa6-50a49b6818aa': 'Hatay',
  'd725a9a0-7a80-5015-9e87-afee888225d2': 'Isparta',
  '01d832aa-97c8-5eba-ae42-200bb7047edb': 'Mersin',
  'c029c5bf-570e-5eb2-9d0f-0437fa131ff1': 'İstanbul',
  '64f1681f-bd67-5b6d-a0fb-cb67e70dda74': 'İzmir',
  '46d0860f-e6f8-5324-ad1d-b493da199075': 'Kars',
  '59e3a858-d837-5f8a-bd15-dad0cb80848d': 'Kastamonu',
  'f7d1fef1-1ccd-5b23-bb91-d8242060ae31': 'Kayseri',
  '1b888d4e-2537-5b9b-b346-921d649e9ab2': 'Kırklareli',
  'a52e9c66-083d-51ae-b906-5fb3589e9a2f': 'Kırşehir',
  '99307140-598f-59c3-b219-892878bd5e7d': 'Kocaeli',
  '43d77888-0432-576d-93ef-24f834c8ebac': 'Konya',
  'f11f3330-fda2-5a35-b476-663501a13b96': 'Kütahya',
  '5df86c75-3a11-5563-a2c1-bd625ec0825b': 'Malatya',
  '5d482e8c-5cef-5cf2-81f1-6b2d2eb6d562': 'Manisa',
  '27ae1aaf-0c3f-50bc-8d84-29bdf5b4cafc': 'Kahramanmaraş',
  'f78b3441-28c7-5b64-9e28-00cb2e2c6c74': 'Mardin',
  '82a6edde-a2ab-5cdb-ae35-5c6c08bee9f4': 'Muğla',
  'bf6e9697-9e72-5d42-b391-a4f177e009a1': 'Muş',
  '7ea80ade-8e79-5287-aa57-b9679b7d2493': 'Nevşehir',
  'c0146c7d-49e6-5eac-ac4e-e6160d099932': 'Niğde',
  'd6b95015-232f-577a-ac05-dc7fd749df79': 'Ordu',
  '31ddec39-08bc-58cf-aac4-a2a5e92a1b75': 'Rize',
  '4ac1103e-e6b8-567b-871e-654699e186c9': 'Sakarya',
  'f23e4ccb-0c68-55c4-a2e0-b93e5628ed30': 'Samsun',
  'e619c5e3-0f52-553a-a5ec-7452f7577871': 'Siirt',
  'ce12c51f-b585-57b1-89f7-a2c26cee920c': 'Sinop',
  '49a980c1-397d-59a7-aa16-c3af6342fc9a': 'Sivas',
  '4885e918-b9eb-5db3-85c2-b8ffa5930b6e': 'Tekirdağ',
  '889abfb3-d544-5628-88ce-8631afaf33e0': 'Tokat',
  'f5e4bc23-3a08-549c-a90f-156c7729e5a6': 'Trabzon',
  'b2bc9402-45c7-53d2-bb5e-da697a76b856': 'Tunceli',
  'ea38567b-7f7f-55bc-a95a-e936c280de19': 'Şanlıurfa',
  '6fc5e62c-1138-57f2-9b03-12f25ab5f1b2': 'Uşak',
  '442c3df1-7610-5540-8a02-59bbb9361359': 'Van',
  'c44beff4-a64a-5c39-9e5d-930d3cfb69b8': 'Yozgat',
  'a7726d7c-e3ab-5272-9c49-4a2fd0ba77bf': 'Zonguldak',
  '8fa4aea9-359d-5066-b935-2f92126144a3': 'Aksaray',
  '3060b17f-2a00-5096-a008-4bd2d17383e7': 'Bayburt',
  '18f1efc7-d5cd-56a3-8e65-ca6de93420fb': 'Karaman',
  '9e2ecc23-1f18-52a5-8af4-653e740f225e': 'Kırıkkale',
  '66f78454-b7d4-596f-abb7-e9aaa7ba8a5a': 'Batman',
  'c40efeab-8ed2-5e0a-8352-0c0fa25178d3': 'Şırnak',
  '9755f927-625a-5986-a3aa-acd4ef20b126': 'Bartın',
  'dc431c2a-03d9-589b-8dc9-a9ccfe1162e1': 'Ardahan',
  'a98d0f3b-748f-5704-a0e9-7489cd654579': 'Iğdır',
  '1fc7e574-b545-5fef-a142-3a974584bb62': 'Yalova',
  '79a22106-cc22-559a-8d33-59c2534bc3a7': 'Karabük',
  '0a076515-a6fa-5d74-9ea4-636eac7622d7': 'Kilis',
  '696d6fc8-e340-5c77-ab2f-675496726aad': 'Osmaniye',
  '921ebfc0-8b4c-5204-a3bc-bc5d8ba86e8f': 'Düzce',
};

const DISTRICTS: Record<string, { name: string; provinceId: string }> = {
  // 01 Adana
  'dist-01-sey': { name: 'Seyhan', provinceId: 'prov-01' },
  'dist-01-cuk': { name: 'Çukurova', provinceId: 'prov-01' },
  'dist-01-yur': { name: 'Yüreğir', provinceId: 'prov-01' },
  'dist-01-cey': { name: 'Ceyhan', provinceId: 'prov-01' },
  'dist-01-koz': { name: 'Kozan', provinceId: 'prov-01' },

  // 02 Adıyaman
  'dist-02-mer': { name: 'Merkez', provinceId: 'prov-02' },
  'dist-02-kah': { name: 'Kahta', provinceId: 'prov-02' },
  'dist-02-bes': { name: 'Besni', provinceId: 'prov-02' },

  // 03 Afyonkarahisar
  'dist-03-mer': { name: 'Merkez', provinceId: 'prov-03' },
  'dist-03-san': { name: 'Sandıklı', provinceId: 'prov-03' },
  'dist-03-din': { name: 'Dinar', provinceId: 'prov-03' },

  // 04 Ağrı
  'dist-04-mer': { name: 'Merkez', provinceId: 'prov-04' },
  'dist-04-dog': { name: 'Doğubayazıt', provinceId: 'prov-04' },
  'dist-04-pat': { name: 'Patnos', provinceId: 'prov-04' },

  // 05 Amasya
  'dist-05-mer': { name: 'Merkez', provinceId: 'prov-05' },
  'dist-05-mrz': { name: 'Merzifon', provinceId: 'prov-05' },
  'dist-05-sul': { name: 'Suluova', provinceId: 'prov-05' },
  'dist-05-tas': { name: 'Taşova', provinceId: 'prov-05' },

  // 06 Ankara
  'dist-06-can': { name: 'Çankaya', provinceId: 'prov-06' },
  'dist-06-kec': { name: 'Keçiören', provinceId: 'prov-06' },
  'dist-06-yen': { name: 'Yenimahalle', provinceId: 'prov-06' },
  'dist-06-mam': { name: 'Mamak', provinceId: 'prov-06' },
  'dist-06-eti': { name: 'Etimesgut', provinceId: 'prov-06' },
  'dist-06-sin': { name: 'Sincan', provinceId: 'prov-06' },
  'dist-06-gol': { name: 'Gölbaşı', provinceId: 'prov-06' },
  'dist-06-cub': { name: 'Çubuk', provinceId: 'prov-06' },
  'dist-06-pol': { name: 'Polatlı', provinceId: 'prov-06' },

  // 07 Antalya
  'dist-07-mur': { name: 'Muratpaşa', provinceId: 'prov-07' },
  'dist-07-kep': { name: 'Kepez', provinceId: 'prov-07' },
  'dist-07-kon': { name: 'Konyaaltı', provinceId: 'prov-07' },
  'dist-07-ala': { name: 'Alanya', provinceId: 'prov-07' },
  'dist-07-man': { name: 'Manavgat', provinceId: 'prov-07' },
  'dist-07-ser': { name: 'Serik', provinceId: 'prov-07' },
  'dist-07-kas': { name: 'Kaş', provinceId: 'prov-07' },
  'dist-07-kem': { name: 'Kemer', provinceId: 'prov-07' },

  // 08 Artvin
  'dist-08-mer': { name: 'Merkez', provinceId: 'prov-08' },
  'dist-08-hop': { name: 'Hopa', provinceId: 'prov-08' },

  // 09 Aydın
  'dist-09-efe': { name: 'Efeler', provinceId: 'prov-09' },
  'dist-09-kus': { name: 'Kuşadası', provinceId: 'prov-09' },
  'dist-09-sok': { name: 'Söke', provinceId: 'prov-09' },
  'dist-09-naz': { name: 'Nazilli', provinceId: 'prov-09' },

  // 10 Balıkesir
  'dist-10-kar': { name: 'Karesi', provinceId: 'prov-10' },
  'dist-10-alt': { name: 'Altıeylül', provinceId: 'prov-10' },
  'dist-10-ban': { name: 'Bandırma', provinceId: 'prov-10' },
  'dist-10-edr': { name: 'Edremit', provinceId: 'prov-10' },
  'dist-10-ayv': { name: 'Ayvalık', provinceId: 'prov-10' },

  // 16 Bursa
  'dist-16-osm': { name: 'Osmangazi', provinceId: 'prov-16' },
  'dist-16-yil': { name: 'Yıldırım', provinceId: 'prov-16' },
  'dist-16-nil': { name: 'Nilüfer', provinceId: 'prov-16' },
  'dist-16-ine': { name: 'İnegöl', provinceId: 'prov-16' },
  'dist-16-gem': { name: 'Gemlik', provinceId: 'prov-16' },
  'dist-16-mud': { name: 'Mudanya', provinceId: 'prov-16' },

  // 20 Denizli
  'dist-20-pam': { name: 'Pamukkale', provinceId: 'prov-20' },
  'dist-20-mer': { name: 'Merkezefendi', provinceId: 'prov-20' },

  // 21 Diyarbakır
  'dist-21-kay': { name: 'Kayapınar', provinceId: 'prov-21' },
  'dist-21-bag': { name: 'Bağlar', provinceId: 'prov-21' },
  'dist-21-yen': { name: 'Yenişehir', provinceId: 'prov-21' },

  // 25 Erzurum
  'dist-25-yak': { name: 'Yakutiye', provinceId: 'prov-25' },
  'dist-25-pal': { name: 'Palandöken', provinceId: 'prov-25' },

  // 26 Eskişehir
  'dist-26-odu': { name: 'Odunpazarı', provinceId: 'prov-26' },
  'dist-26-tep': { name: 'Tepebaşı', provinceId: 'prov-26' },

  // 27 Gaziantep
  'dist-27-sah': { name: 'Şahinbey', provinceId: 'prov-27' },
  'dist-27-seh': { name: 'Şehitkamil', provinceId: 'prov-27' },
  'dist-27-niz': { name: 'Nizip', provinceId: 'prov-27' },

  // 31 Hatay
  'dist-31-ant': { name: 'Antakya', provinceId: 'prov-31' },
  'dist-31-isk': { name: 'İskenderun', provinceId: 'prov-31' },

  // 33 Mersin
  'dist-33-yen': { name: 'Yenişehir', provinceId: 'prov-33' },
  'dist-33-tor': { name: 'Toroslar', provinceId: 'prov-33' },
  'dist-33-mez': { name: 'Mezitli', provinceId: 'prov-33' },
  'dist-33-tar': { name: 'Tarsus', provinceId: 'prov-33' },

  // 34 İstanbul
  'dist-34-kad': { name: 'Kadıköy', provinceId: 'prov-34' },
  'dist-34-bes': { name: 'Beşiktaş', provinceId: 'prov-34' },
  'dist-34-sis': { name: 'Şişli', provinceId: 'prov-34' },
  'dist-34-usk': { name: 'Üsküdar', provinceId: 'prov-34' },
  'dist-34-cek': { name: 'Çekmeköy', provinceId: 'prov-34' },
  'dist-34-sil': { name: 'Silivri', provinceId: 'prov-34' },
  'dist-34-bak': { name: 'Bakırköy', provinceId: 'prov-34' },
  'dist-34-mal': { name: 'Maltepe', provinceId: 'prov-34' },
  'dist-34-pen': { name: 'Pendik', provinceId: 'prov-34' },
  'dist-34-fat': { name: 'Fatih', provinceId: 'prov-34' },
  'dist-34-bey': { name: 'Beyoğlu', provinceId: 'prov-34' },
  'dist-34-sar': { name: 'Sarıyer', provinceId: 'prov-34' },
  'dist-34-ata': { name: 'Ataşehir', provinceId: 'prov-34' },
  'dist-34-umr': { name: 'Ümraniye', provinceId: 'prov-34' },
  'dist-34-bas': { name: 'Başakşehir', provinceId: 'prov-34' },
  'dist-34-bld': { name: 'Beylikdüzü', provinceId: 'prov-34' },

  // 35 İzmir
  'dist-35-kon': { name: 'Konak', provinceId: 'prov-35' },
  'dist-35-ksk': { name: 'Karşıyaka', provinceId: 'prov-35' },
  'dist-35-bor': { name: 'Bornova', provinceId: 'prov-35' },
  'dist-35-buc': { name: 'Buca', provinceId: 'prov-35' },
  'dist-35-tor': { name: 'Torbalı', provinceId: 'prov-35' },
  'dist-35-ces': { name: 'Çeşme', provinceId: 'prov-35' },
  'dist-35-url': { name: 'Urla', provinceId: 'prov-35' },

  // 38 Kayseri
  'dist-38-mel': { name: 'Melikgazi', provinceId: 'prov-38' },
  'dist-38-koc': { name: 'Kocasinan', provinceId: 'prov-38' },
  'dist-38-tal': { name: 'Talas', provinceId: 'prov-38' },

  // 41 Kocaeli
  'dist-41-izm': { name: 'İzmit', provinceId: 'prov-41' },
  'dist-41-geb': { name: 'Gebze', provinceId: 'prov-41' },
  'dist-41-dar': { name: 'Darıca', provinceId: 'prov-41' },
  'dist-41-gol': { name: 'Gölcük', provinceId: 'prov-41' },

  // 42 Konya
  'dist-42-sel': { name: 'Selçuklu', provinceId: 'prov-42' },
  'dist-42-mer': { name: 'Meram', provinceId: 'prov-42' },
  'dist-42-kar': { name: 'Karatay', provinceId: 'prov-42' },
  'dist-42-ere': { name: 'Ereğli', provinceId: 'prov-42' },

  // 44 Malatya
  'dist-44-yes': { name: 'Yeşilyurt', provinceId: 'prov-44' },
  'dist-44-bat': { name: 'Battalgazi', provinceId: 'prov-44' },

  // 45 Manisa
  'dist-45-yun': { name: 'Yunusemre', provinceId: 'prov-45' },
  'dist-45-seh': { name: 'Şehzadeler', provinceId: 'prov-45' },
  'dist-45-akh': { name: 'Akhisar', provinceId: 'prov-45' },

  // 46 Kahramanmaraş
  'dist-46-oni': { name: 'Onikişubat', provinceId: 'prov-46' },
  'dist-46-dul': { name: 'Dulkadiroğlu', provinceId: 'prov-46' },

  // 47 Mardin
  'dist-47-art': { name: 'Artuklu', provinceId: 'prov-47' },
  'dist-47-kiz': { name: 'Kızıltepe', provinceId: 'prov-47' },
  'dist-47-mid': { name: 'Midyat', provinceId: 'prov-47' },

  // 48 Muğla
  'dist-48-men': { name: 'Menteşe', provinceId: 'prov-48' },
  'dist-48-bod': { name: 'Bodrum', provinceId: 'prov-48' },
  'dist-48-fet': { name: 'Fethiye', provinceId: 'prov-48' },
  'dist-48-mar': { name: 'Marmaris', provinceId: 'prov-48' },

  // 54 Sakarya
  'dist-54-ada': { name: 'Adapazarı', provinceId: 'prov-54' },
  'dist-54-ser': { name: 'Serdivan', provinceId: 'prov-54' },

  // 55 Samsun
  'dist-55-ata': { name: 'Atakum', provinceId: 'prov-55' },
  'dist-55-ilk': { name: 'İlkadım', provinceId: 'prov-55' },
  'dist-55-baf': { name: 'Bafra', provinceId: 'prov-55' },

  // 59 Tekirdağ
  'dist-59-sul': { name: 'Süleymanpaşa', provinceId: 'prov-59' },
  'dist-59-cor': { name: 'Çorlu', provinceId: 'prov-59' },
  'dist-59-cer': { name: 'Çerkezköy', provinceId: 'prov-59' },

  // 61 Trabzon
  'dist-61-ort': { name: 'Ortahisar', provinceId: 'prov-61' },
  'dist-61-akc': { name: 'Akçaabat', provinceId: 'prov-61' },

  // 63 Şanlıurfa
  'dist-63-hal': { name: 'Haliliye', provinceId: 'prov-63' },
  'dist-63-eyy': { name: 'Eyyübiye', provinceId: 'prov-63' },
  'dist-63-kar': { name: 'Karaköprü', provinceId: 'prov-63' },
  'dist-63-siv': { name: 'Siverek', provinceId: 'prov-63' },

  // 65 Van
  'dist-65-ipe': { name: 'İpekyolu', provinceId: 'prov-65' },
  'dist-65-tus': { name: 'Tuşba', provinceId: 'prov-65' },

  // 67 Zonguldak
  'dist-67-mer': { name: 'Merkez', provinceId: 'prov-67' },
  'dist-67-ere': { name: 'Ereğli', provinceId: 'prov-67' },

  // 77 Yalova
  'dist-77-mer': { name: 'Merkez', provinceId: 'prov-77' },
  'dist-77-cin': { name: 'Çınarcık', provinceId: 'prov-77' },

  // 81 Düzce
  'dist-81-mer': { name: 'Merkez', provinceId: 'prov-81' },
  'dist-81-akc': { name: 'Akçakoca', provinceId: 'prov-81' },
};

export class StaticLocationLookup implements ILocationLookup {
  private readonly dynamicProvinces = new Map<string, string>();
  private readonly dynamicDistricts = new Map<string, { name: string; provinceId: string }>();
  private readonly listeners = new Set<() => void>();

  subscribe(listener: () => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  private notifyListeners(): void {
    this.listeners.forEach((listener) => {
      try {
        listener();
      } catch {
        // ignore listener errors
      }
    });
  }

  registerProvince(provinceId: string, name: string): void {
    if (!provinceId || !name) return;
    const cleanId = provinceId.trim();
    const cleanName = name.trim();
    if (cleanId && cleanName) {
      this.dynamicProvinces.set(cleanId, cleanName);
      this.dynamicProvinces.set(cleanId.toLowerCase(), cleanName);
      this.notifyListeners();
    }
  }

  registerDistrict(districtId: string, name: string, provinceId?: string): void {
    if (!districtId || !name) return;
    const cleanId = districtId.trim();
    const cleanName = name.trim();
    if (cleanId && cleanName) {
      this.dynamicDistricts.set(cleanId, { name: cleanName, provinceId: provinceId ?? '' });
      this.dynamicDistricts.set(cleanId.toLowerCase(), { name: cleanName, provinceId: provinceId ?? '' });
      this.notifyListeners();
    }
  }

  getProvinceName(provinceId: string | null | undefined): string {
    if (!provinceId) return '';
    const key = String(provinceId).trim();
    if (!key) return '';

    // Check dynamic register first
    if (this.dynamicProvinces.has(key)) return this.dynamicProvinces.get(key)!;
    if (this.dynamicProvinces.has(key.toLowerCase())) return this.dynamicProvinces.get(key.toLowerCase())!;

    // Check by code (prov-01 .. prov-81)
    if (PROVINCES_BY_CODE[key]) return PROVINCES_BY_CODE[key];
    if (PROVINCES_BY_CODE[key.toLowerCase()]) return PROVINCES_BY_CODE[key.toLowerCase()];

    // Check by UUID v5
    if (PROVINCES_BY_UUID[key]) return PROVINCES_BY_UUID[key];
    if (PROVINCES_BY_UUID[key.toLowerCase()]) return PROVINCES_BY_UUID[key.toLowerCase()];

    // Check if plate number e.g. "34", "06", 34
    const plateNum = parseInt(key, 10);
    if (!isNaN(plateNum) && plateNum >= 1 && plateNum <= 81) {
      const code = `prov-${String(plateNum).padStart(2, '0')}`;
      if (PROVINCES_BY_CODE[code]) return PROVINCES_BY_CODE[code];
    }

    // Check if already a known province name
    for (const name of Object.values(PROVINCES_BY_CODE)) {
      if (name.localeCompare(key, 'tr', { sensitivity: 'accent' }) === 0) {
        return name;
      }
    }

    return '';
  }

  getDistrictName(districtId: string | null | undefined): string {
    if (!districtId) return '';
    const key = String(districtId).trim();
    if (!key) return '';

    // Check dynamic register first
    if (this.dynamicDistricts.has(key)) return this.dynamicDistricts.get(key)!.name;
    if (this.dynamicDistricts.has(key.toLowerCase())) return this.dynamicDistricts.get(key.toLowerCase())!.name;

    // Check in DISTRICTS dictionary
    if (DISTRICTS[key]) return DISTRICTS[key].name;
    if (DISTRICTS[key.toLowerCase()]) return DISTRICTS[key.toLowerCase()].name;

    // Pattern dist-XX-name or dist-XX
    if (key.startsWith('dist-')) {
      const parts = key.split('-');
      if (parts.length >= 2) {
        const provCode = `prov-${parts[1]}`;
        const provName = this.getProvinceName(provCode);
        if (parts.length >= 3) {
          const suffix = parts[2].toLowerCase();
          if (suffix === 'mer' || suffix === 'merkez') {
            return provName ? `${provName} Merkez` : 'Merkez';
          }
        }
        if (provName) return `${provName} Merkez`;
      }
    }

    return '';
  }

  formatLocation(
    districtId?: string | null,
    provinceId?: string | null,
    districtName?: string | null,
    provinceName?: string | null
  ): string {
    const dist = (districtName && districtName.trim()) || this.getDistrictName(districtId);
    const prov = (provinceName && provinceName.trim()) || this.getProvinceName(provinceId);

    if (dist && prov) {
      if (dist.toLowerCase() === prov.toLowerCase()) return prov;
      return `${dist}, ${prov}`;
    }
    if (dist) return dist;
    if (prov) return prov;
    return '';
  }

  async listProvinces(): Promise<ProvinceOption[]> {
    return Object.entries(PROVINCES_BY_CODE)
      .map(([id, name]) => ({ id, name }))
      .sort((a, b) => a.name.localeCompare(b.name, 'tr'));
  }

  async listDistricts(provinceId: string): Promise<DistrictOption[]> {
    const cleanId = (provinceId || '').trim();
    const list = Object.entries(DISTRICTS)
      .filter(([, d]) => d.provinceId === cleanId || this.getProvinceName(d.provinceId) === this.getProvinceName(cleanId))
      .map(([id, d]) => ({ id, provinceId: d.provinceId, name: d.name }))
      .sort((a, b) => a.name.localeCompare(b.name, 'tr'));

    if (list.length > 0) return list;

    const provinceName = this.getProvinceName(cleanId);
    if (provinceName) {
      return [{ id: `dist-${cleanId}-merkez`, provinceId: cleanId, name: `${provinceName} Merkez` }];
    }
    return [];
  }

  invalidate(): void {
    this.dynamicProvinces.clear();
    this.dynamicDistricts.clear();
  }
}
